### ISSUE TITLE
Plasma 5 panel crashes if playlist is empty

### ISSUE THREAD

**Issue by joharei** [mopidy/mopidy-mpris#17]
Not sure if this issue is with mopidy-mpris or the Plasma media player widget. When the playlist in mopidy is empty (for instance on first start or when explicitly clearing the playlist), Plasma crashes. If the playlist is not empty, everything works well.

Please tell me if I can provide any useful debugging.

**Comment by jodal** [comment]
I didn't know KDE(?)/Plasma had an MPRIS client. I don't have a KDE setup anywhere, so I won't get around to test this in the near future. Keep me updated if you dig into this.

**Comment by joharei** [comment]
It does, but I can't find much info on it. The widget appears when some application using mpris is running. And I haven't had this problem with other music players.

**Comment by adamcik** [comment]
https://bugs.kde.org/show_bug.cgi?id=352008

**Comment by novalu** [comment]
I have same problem, but luckily this [bug](https://bugs.kde.org/show_bug.cgi?id=374531) has fixed in KDE Plasma 5.8.6, which was [released yesterday](https://www.kde.org/announcements/plasma-5.8.6.php). (I've not tried fix, as I waiting for update in [Kubuntu backports](https://kubuntu.org/news/plasma-5-8-5-bugfix-release-in-xenial-and-yakkety-backports-now/), usually 5-10 days after bugfix release)

**Comment by jodal** [comment]
Quoting https://bugs.kde.org/show_bug.cgi?id=374531:

> [MPRIS Data Engine] Don't crash if "Metadata" is a map but of wrong type
> 
> QDBusArgument MapType fits all kinds of maps but when we try to stream a map of type
other than a{sv} (which the MRPIS spec requires) into a QVariantMap we would crash.
Explicitly check signature to avoid this.

This will be fixed on the Mopidy-MPRIS end by the merge of PR #21.

**Comment by jodal** [comment]
I can confirm that this has been fixed in the master branch, which will be released as v2.0.0 soon.

The following configuration enforces what Mopidy-MPRIS now exposes as the `Metadata` property: https://github.com/mopidy/mopidy-mpris/blob/6a29a273c8994b08c8183c8a3100d641b531de79/mopidy_mpris/player.py#L49
